# Generated by Django 3.2.4 on 2022-08-05 17:35

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api_payment', '0002_invoice_nomor_urut'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='nomor_urut',
        ),
        migrations.CreateModel(
            name='PaymentTransfer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(blank=True, db_column='email', max_length=1000, null=True, verbose_name='Email')),
                ('payment_type', models.CharField(blank=True, db_column='payment_type', max_length=1000, null=True, verbose_name='Payment type')),
                ('bank', models.CharField(blank=True, db_column='bank', max_length=1000, null=True, verbose_name='Bank')),
                ('virtual_account', models.IntegerField(blank=True, db_column='virtual_account', null=True, verbose_name='Virtual Account')),
                ('time_remaining', models.CharField(blank=True, db_column='time_remaining', max_length=1000, null=True, verbose_name='Time remaining')),
                ('total_amount', models.IntegerField(blank=True, db_column='total_amount', null=True, verbose_name='Total amount')),
                ('status', models.CharField(blank=True, db_column='status', default='pending', max_length=1000, null=True, verbose_name='Status')),
                ('createdAt', models.DateTimeField(blank=True, db_column='createdAt', default=django.utils.timezone.now, null=True, verbose_name='Created At')),
                ('createdBy', models.IntegerField(blank=True, db_column='createdBy', null=True, verbose_name='Created By')),
                ('modifiedAt', models.DateTimeField(blank=True, db_column='modifiedAt', null=True, verbose_name='Modified At')),
                ('modifiedBy', models.IntegerField(blank=True, db_column='modifiedBy', null=True, verbose_name='Modified By')),
                ('accountId', models.IntegerField(blank=True, db_column='accountId', null=True, verbose_name='Account Id')),
                ('invoice', models.ForeignKey(blank=True, db_column='invoice_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='api_payment.invoice')),
            ],
            options={
                'db_table': 'tbl_payment_transfer',
            },
        ),
        migrations.CreateModel(
            name='PaymentCard',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(blank=True, db_column='email', max_length=1000, null=True, verbose_name='Email')),
                ('payment_type', models.CharField(blank=True, db_column='payment_type', max_length=1000, null=True, verbose_name='Payment type')),
                ('first_name', models.CharField(blank=True, db_column='first_name', max_length=1000, null=True, verbose_name='First name')),
                ('last_name', models.CharField(blank=True, db_column='last_name', max_length=1000, null=True, verbose_name='Last name')),
                ('card_number', models.IntegerField(blank=True, db_column='card_number', null=True, verbose_name='Card number')),
                ('valid_thru', models.CharField(blank=True, db_column='valid_thru', max_length=1000, null=True, verbose_name='Valid thru')),
                ('cvv', models.IntegerField(blank=True, db_column='cvv', null=True, verbose_name='Cvv')),
                ('otp', models.IntegerField(blank=True, db_column='otp', null=True, verbose_name='Otp')),
                ('total_amount', models.IntegerField(blank=True, db_column='total_amount', null=True, verbose_name='Total amount')),
                ('status', models.CharField(blank=True, db_column='status', default='pending', max_length=1000, null=True, verbose_name='Status')),
                ('createdAt', models.DateTimeField(blank=True, db_column='createdAt', default=django.utils.timezone.now, null=True, verbose_name='Created At')),
                ('createdBy', models.IntegerField(blank=True, db_column='createdBy', null=True, verbose_name='Created By')),
                ('modifiedAt', models.DateTimeField(blank=True, db_column='modifiedAt', null=True, verbose_name='Modified At')),
                ('modifiedBy', models.IntegerField(blank=True, db_column='modifiedBy', null=True, verbose_name='Modified By')),
                ('accountId', models.IntegerField(blank=True, db_column='accountId', null=True, verbose_name='Account Id')),
                ('invoice', models.ForeignKey(blank=True, db_column='invoice_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='api_payment.invoice')),
            ],
            options={
                'db_table': 'tbl_payment_card',
            },
        ),
    ]
