# Generated by Django 3.2.4 on 2022-08-05 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_payment', '0004_alter_paymenttransfer_virtual_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='total_amount',
            field=models.DecimalField(blank=True, db_column='total_amount', decimal_places=10, max_digits=70, null=True, verbose_name='Total amount'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='total_amount',
            field=models.DecimalField(blank=True, db_column='total_amount', decimal_places=10, max_digits=70, null=True, verbose_name='Total amount'),
        ),
        migrations.AlterField(
            model_name='paymentcard',
            name='total_amount',
            field=models.DecimalField(blank=True, db_column='total_amount', decimal_places=10, max_digits=70, null=True, verbose_name='Total amount'),
        ),
        migrations.AlterField(
            model_name='paymenttransfer',
            name='total_amount',
            field=models.DecimalField(blank=True, db_column='total_amount', decimal_places=10, max_digits=70, null=True, verbose_name='Total amount'),
        ),
    ]
