# Generated by Django 3.2.4 on 2022-08-05 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_payment', '0005_auto_20220805_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='total_amount',
            field=models.FloatField(blank=True, db_column='total_amount', null=True, verbose_name='Total amount'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='total_amount',
            field=models.FloatField(blank=True, db_column='total_amount', null=True, verbose_name='Total amount'),
        ),
        migrations.AlterField(
            model_name='paymentcard',
            name='total_amount',
            field=models.FloatField(blank=True, db_column='total_amount', null=True, verbose_name='Total amount'),
        ),
        migrations.AlterField(
            model_name='paymenttransfer',
            name='total_amount',
            field=models.FloatField(blank=True, db_column='total_amount', null=True, verbose_name='Total amount'),
        ),
    ]
