# Generated by Django 3.2.4 on 2022-09-13 07:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api_payment', '0007_auto_20220913_0646'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='status',
        ),
        migrations.AddField(
            model_name='invoice',
            name='payment_date',
            field=models.DateTimeField(blank=True, db_column='payment_date', default=django.utils.timezone.now, null=True, verbose_name='Payment Date'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='payment_status',
            field=models.CharField(blank=True, db_column='payment_status', default='pending', max_length=1000, null=True, verbose_name='Payment Status'),
        ),
    ]
