# Generated by Django 3.2.4 on 2022-09-14 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_payment', '0008_auto_20220913_0755'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='tax',
            field=models.FloatField(blank=True, db_column='tax', null=True, verbose_name='Tax'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='total_price_user',
            field=models.FloatField(blank=True, db_column='total_price_user', null=True, verbose_name='Total Price User'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='sub_total',
            field=models.FloatField(blank=True, db_column='sub_total', null=True, verbose_name='Sub total'),
        ),
    ]
