# Generated by Django 3.2.4 on 2022-09-30 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_payment', '0011_auto_20220929_0834'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransfer',
            name='bill_key',
            field=models.CharField(blank=True, db_column='bill_key', max_length=1000, null=True, verbose_name='bill key'),
        ),
        migrations.AddField(
            model_name='paymenttransfer',
            name='biller_code',
            field=models.CharField(blank=True, db_column='biller_code', max_length=1000, null=True, verbose_name='biller code'),
        ),
        migrations.AddField(
            model_name='paymenttransfer',
            name='order_id',
            field=models.CharField(blank=True, db_column='order_id', max_length=1000, null=True, verbose_name='order id'),
        ),
        migrations.AddField(
            model_name='paymenttransfer',
            name='transaction_id',
            field=models.CharField(blank=True, db_column='transaction_id', max_length=1000, null=True, verbose_name='transaction id'),
        ),
    ]
