# Generated by Django 3.2.4 on 2022-10-09 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_payment', '0015_auto_20220930_0919'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentcard',
            name='order_id',
            field=models.CharField(blank=True, db_column='order_id', max_length=1000, null=True, verbose_name='order id'),
        ),
        migrations.AddField(
            model_name='paymentcard',
            name='redicret_url',
            field=models.CharField(blank=True, db_column='redicret_url', max_length=1000, null=True, verbose_name='redicret url'),
        ),
        migrations.AddField(
            model_name='paymentcard',
            name='transaction_id',
            field=models.CharField(blank=True, db_column='transaction_id', max_length=1000, null=True, verbose_name='transaction id'),
        ),
    ]
