# Generated by Django 3.2.4 on 2022-10-09 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_payment', '0018_auto_20221009_0406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentcard',
            name='card_number',
            field=models.BigIntegerField(blank=True, db_column='card_number', null=True, verbose_name='Card number'),
        ),
    ]
