# Generated by Django 3.2.4 on 2022-11-29 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_payment', '0019_alter_paymentcard_card_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(blank=True, db_column='status', default='running', max_length=1000, null=True, verbose_name='Status'),
        ),
    ]
