# Generated by Django 3.2.4 on 2022-12-01 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_payment', '0020_alter_invoice_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='exp_date',
        ),
        migrations.AddField(
            model_name='invoice',
            name='expired_date',
            field=models.DateTimeField(blank=True, db_column='expired_date', null=True, verbose_name='Expiration Date'),
        ),
    ]
