# Generated by Django 3.2.4 on 2022-12-23 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_payment', '0021_auto_20221201_1118'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(blank=True, db_column='type', max_length=1000, null=True, verbose_name='type')),
                ('priceuser', models.BigIntegerField(blank=True, db_column='price_user', null=True, verbose_name='price user')),
                ('periode', models.CharField(blank=True, db_column='periode', max_length=1000, null=True, verbose_name='periode')),
                ('name', models.CharField(blank=True, db_column='name', max_length=1000, null=True, verbose_name='name')),
                ('picture', models.CharField(blank=True, db_column='picture', max_length=1000, null=True, verbose_name='picture')),
                ('bank', models.CharField(blank=True, db_column='bank', max_length=1000, null=True, verbose_name='Bank')),
            ],
            options={
                'db_table': 'tbl_setting',
            },
        ),
    ]
