# Generated by Django 3.2.4 on 2022-12-27 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_payment', '0022_setting'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='update_core',
            field=models.BooleanField(db_column='update_core', default=False, verbose_name='update core'),
        ),
    ]
