# Generated by Django 3.2.4 on 2023-03-06 14:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api_payment', '0023_invoice_update_core'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='payment_type',
            field=models.CharField(blank=True, db_column='payment_type', max_length=1000, null=True, verbose_name='Payment type'),
        ),
        migrations.CreateModel(
            name='PaymentTransferManual',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(blank=True, db_column='email', max_length=1000, null=True, verbose_name='Email')),
                ('name', models.CharField(blank=True, db_column='name', max_length=1000, null=True, verbose_name='name')),
                ('nomor_rekening', models.IntegerField(blank=True, db_column='nomor_rekening', null=True, verbose_name='nomor rekening')),
                ('payment_type', models.CharField(blank=True, db_column='payment_type', max_length=1000, null=True, verbose_name='Payment type')),
                ('bank', models.CharField(blank=True, db_column='bank', max_length=1000, null=True, verbose_name='Bank')),
                ('expired', models.DateTimeField(blank=True, db_column='expired', null=True, verbose_name='expired')),
                ('transaction_time', models.DateTimeField(blank=True, db_column='transaction_time', null=True, verbose_name='transaction time')),
                ('total_amount', models.FloatField(blank=True, db_column='total_amount', null=True, verbose_name='Total amount')),
                ('status', models.CharField(blank=True, db_column='status', default='pending', max_length=1000, null=True, verbose_name='Status')),
                ('createdAt', models.DateTimeField(blank=True, db_column='createdAt', default=django.utils.timezone.now, null=True, verbose_name='Created At')),
                ('createdBy', models.IntegerField(blank=True, db_column='createdBy', null=True, verbose_name='Created By')),
                ('modifiedAt', models.DateTimeField(blank=True, db_column='modifiedAt', null=True, verbose_name='Modified At')),
                ('modifiedBy', models.IntegerField(blank=True, db_column='modifiedBy', null=True, verbose_name='Modified By')),
                ('accountId', models.IntegerField(blank=True, db_column='accountId', null=True, verbose_name='Account Id')),
                ('invoice', models.ForeignKey(blank=True, db_column='invoice_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='api_payment.invoice')),
            ],
            options={
                'db_table': 'tbl_payment_manual',
            },
        ),
    ]
