# Generated by Django 3.2.4 on 2023-03-06 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_payment', '0025_auto_20230306_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='bank_account_name',
            field=models.CharField(blank=True, db_column='bank_account_name', max_length=1000, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='setting',
            name='bank_account_number',
            field=models.IntegerField(blank=True, db_column='bank_account_number', null=True, verbose_name='nomor rekening'),
        ),
    ]
