# Generated by Django 3.2.4 on 2023-03-06 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_payment', '0026_auto_20230306_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttransfermanual',
            name='bank_account_number',
            field=models.BigIntegerField(blank=True, db_column='bank_account_number', null=True, verbose_name='nomor rekening'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='bank_account_number',
            field=models.BigIntegerField(blank=True, db_column='bank_account_number', null=True, verbose_name='nomor rekening'),
        ),
    ]
