# Generated by Django 3.2.4 on 2023-03-06 15:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api_payment', '0027_auto_20230306_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttransfermanual',
            name='transaction_time',
            field=models.DateTimeField(blank=True, db_column='transaction_time', default=django.utils.timezone.now, null=True, verbose_name='transaction time'),
        ),
    ]
