# Generated by Django 3.2.4 on 2023-03-09 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_payment', '0028_alter_paymenttransfermanual_transaction_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransfermanual',
            name='proof',
            field=models.CharField(blank=True, db_column='proof', max_length=1000, null=True, verbose_name='Proof'),
        ),
    ]
