# Generated by Django 3.2.4 on 2023-03-16 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_payment', '0032_auto_20230309_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentcard',
            name='expired',
            field=models.DateTimeField(blank=True, db_column='expired', null=True, verbose_name='expired'),
        ),
        migrations.AddField(
            model_name='paymenttransfer',
            name='expired',
            field=models.DateTimeField(blank=True, db_column='expired', null=True, verbose_name='expired'),
        ),
    ]
