# Generated by Django 3.2.4 on 2023-04-27 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_payment', '0034_invoice_account_expired'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentcard',
            name='bank',
        ),
        migrations.RemoveField(
            model_name='paymentcard',
            name='otp',
        ),
        migrations.RemoveField(
            model_name='paymentcard',
            name='redirect_url',
        ),
        migrations.RemoveField(
            model_name='paymentcard',
            name='transaction_id',
        ),
        migrations.AddField(
            model_name='paymentcard',
            name='charge_id',
            field=models.CharField(blank=True, db_column='charge_id', max_length=1000, null=True, verbose_name='charge id'),
        ),
        migrations.AddField(
            model_name='paymentcard',
            name='charge_status',
            field=models.CharField(blank=True, db_column='charge_status', max_length=1000, null=True, verbose_name='charge status'),
        ),
        migrations.AddField(
            model_name='paymentcard',
            name='mask_card_number',
            field=models.CharField(blank=True, db_column='mask_card_number', max_length=1000, null=True, verbose_name='Mask Card number'),
        ),
        migrations.AddField(
            model_name='paymentcard',
            name='payer_authentication_url',
            field=models.CharField(blank=True, db_column='payer_authentication_url', max_length=1000, null=True, verbose_name='payer authentication url'),
        ),
        migrations.AddField(
            model_name='paymentcard',
            name='token_id',
            field=models.CharField(blank=True, db_column='token_id', max_length=1000, null=True, verbose_name='token id'),
        ),
    ]
