# Generated by Django 3.2.4 on 2023-04-27 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_payment', '0035_auto_20230427_0150'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentcard',
            name='card_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
