# Generated by Django 3.2.4 on 2023-05-04 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_payment', '0036_paymentcard_card_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentcard',
            name='bank',
            field=models.CharField(blank=True, db_column='bank', max_length=1000, null=True, verbose_name='Bank'),
        ),
        migrations.AddField(
            model_name='paymentcard',
            name='brand',
            field=models.CharField(blank=True, db_column='brand', max_length=1000, null=True, verbose_name='Brand'),
        ),
    ]
